### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by carlospalavecino** [carlospalavecino/boxify#2]
# RoadMap

## boxify-0.1.0 -> Proof of concept

- [ ] Download a Mac Installer and create an ISO
- [ ] Download a Linux iso file from cmd
- [ ] create a box from a running vm

##  boxify-0.2.0 -> Download Menu

- [ ] Create a selectable Menu for families download
- [ ] Create a selectable menu for each family
- [ ] Add a full list of downloads

## boxify-0.3.0 -> Add host protection 

- [ ] MacOs family could be available only for MacOS Host's

## boxify-0.4.0 -> Add box config

- [ ] Add box configurations
